#!/usr/bin/env python3
"""
Michi Music Stream Simulator — canonical receiver v1-lite.

Simulates a Michi Music Stream receiver (Standard or Hi-Fi) conforming to
the canonical v1-lite contract published by Michi Link (vendored bundle in
contracts/michi-link/). No legacy routes exist:

  GET    /api/v1/server/info
  POST   /api/v1/pair/start
  GET    /api/v1/pair/status?session_id=<uuid>
  POST   /api/v1/pair/confirm
  POST   /api/v1/receiver-lite/session
  GET    /api/v1/receiver-lite/session
  PATCH  /api/v1/receiver-lite/session
  DELETE /api/v1/receiver-lite/session
  POST   /api/v1/receiver-lite/heartbeat

Identity is a deterministic fixture (the identity vector of the vendored
bundle); it is never generated randomly at runtime. The pairing window is
opened by an internal hook (state.open_pairing_window), never by an HTTP
endpoint. Pairing tokens are generated by the receiver (32 CSPRNG bytes,
base64url without padding) and only their SHA-256 digest is kept.

Usage:
  python3 receiver_sim.py --type standard
  python3 receiver_sim.py --type hifi --port 8081
  python3 receiver_sim.py --config config.json

Requires: flask, jsonschema (pip install -r requirements.txt)
"""

import argparse
import base64
import hashlib
import hmac
import json
import logging
import os
import secrets
import socket
import sys
import time
import uuid
from datetime import datetime, timezone

import blake3
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

try:
    from flask import Flask, request, jsonify
except ImportError:
    print("ERROR: flask is required. Install with: pip install flask")
    sys.exit(1)

import jsonschema
from jsonschema import Draft7Validator
from referencing import Registry, Resource

_B64URL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"


def decode_base64url_strict(value):
    if not isinstance(value, str) or not value or value.endswith("="):
        raise ValueError("invalid base64url (padding not allowed)")
    if any(ch not in _B64URL_ALPHABET for ch in value):
        raise ValueError("invalid base64url character")
    return base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))


def derive_michi_id(public_key_bytes):
    return base64.urlsafe_b64encode(blake3.blake3(public_key_bytes).digest()).decode("ascii").rstrip("=")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger("michi-sim")

PAIRING_WINDOW_SECONDS = 120
MAX_PIN_ATTEMPTS = 5
SESSION_LEASE_SECONDS = 30
STREAM_PORT_MIN = 49152
STREAM_PORT_MAX = 65535
TOKEN_BYTES = 32

VECTOR_SERVER_ID = "550e8400-e29b-41d4-a716-446655440000"
VECTOR_MICHI_ID = "f2UwxQaeA6vA8LO7Cr1nGRr5MStned_Gbmc_ua48qUc"
VECTOR_PUBLIC_KEY = "RpHnJr9oP1DXBkPuIMuk0hJ2hAJ5SiWO2hAQVCMGREE"
VECTOR_NAME = "Michi Stream Cocina"
VECTOR_VERSION = "0.3.0"

CONTROLLER_IDENTITY = {
    "device_name": "Michi Micro Server",
    "device_type": "server",
    "roles": ["music_server"],
    "auth_strategy": "RECEIVER_BUTTON",
    "michi_id": "JXcHys3oHoK2xsmQqlWEKi-KH_s4TrxJGw3YbiKP9-U",
    "public_key": "j8oIHv906goIsvcANXl_SZX8-OPcZftDkTPwTYaQQ7E",
    "challenge_nonce": "CxIZICcuNTxDSlFYX2ZtdA",
    "challenge_signature": "5Hg1TwCbzj-x6MaU7mvToRCALEyQXtRKmeJWLmShuXuJWSes16wGptbq573FfY3_H5VWRxPU9LI8hanyNfbXCA",
}

WIFI_BACKOFF_BASE_S = 5.0
WIFI_BACKOFF_MAX_S = 300.0


def _receiver_config(service):
    return {
        "service": service,
        "name": VECTOR_NAME,
        "server_id": VECTOR_SERVER_ID,
        "version": VECTOR_VERSION,
        "api_version": "v1-lite",
        "roles": ["audio_receiver"],
        "identity_scheme": "ed25519-blake3-v1",
        "michi_id": VECTOR_MICHI_ID,
        "public_key": VECTOR_PUBLIC_KEY,
        "auth": {"required": True, "strategy": "RECEIVER_BUTTON", "token_refresh": False},
        "features": {
            "session": True,
            "heartbeat": True,
            "volume": True,
            "now_playing": False,
            "diagnostics": False,
            "ota": False,
        },
        "audio": {
            "transports": ["rtp_udp"],
            "codecs": ["pcm_s16le"],
            "sample_rates": [48000],
            "bit_depths": [16],
            "channels": [2],
            "packet_ms": [10],
            "payload_types": [97],
            "buffer_ms_min": 50,
            "buffer_ms_max": 500,
        },
    }


STANDARD_CONFIG = _receiver_config("michi-stream-standard")
HIFI_CONFIG = _receiver_config("michi-stream-hifi")


BUNDLE_SCHEMA_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "contracts", "michi-link", "schemas")
)


def _load_vendored_schemas():
    docs = {}
    for name in sorted(os.listdir(BUNDLE_SCHEMA_DIR)):
        if name.endswith(".schema.json"):
            with open(os.path.join(BUNDLE_SCHEMA_DIR, name), encoding="utf-8") as handle:
                docs[name] = json.load(handle)
    return docs


BUNDLE_SCHEMAS = _load_vendored_schemas()
BUNDLE_REGISTRY = Registry().with_resources(
    (doc["$id"], Resource.from_contents(doc)) for doc in BUNDLE_SCHEMAS.values()
)


class RequestError:
    def __init__(self, message, field):
        self.message = message
        self.field = field


def validate_request(schema_name, payload):
    validator = Draft7Validator(BUNDLE_SCHEMAS[schema_name], registry=BUNDLE_REGISTRY)
    errors = list(validator.iter_errors(payload))
    if not errors:
        return None
    error = errors[0]
    field = None
    if error.path:
        field = str(error.path[-1])
    elif error.validator == "required" and error.validator_value:
        field = str(error.validator_value[0])
    return RequestError(error.message, field or "body")


def error_body(code, message, details=None):
    envelope = {
        "code": code,
        "message": message,
        "request_id": str(uuid.uuid4()),
    }
    if details is not None:
        envelope["details"] = details
    return {"error": envelope}


class SimulatorState:
    def __init__(self, config, mono_clock=None, wall_clock=None):
        self.config = config
        self.mono_clock = mono_clock or time.monotonic
        self.wall_clock = wall_clock or time.time
        self.boot_mono = self.mono_clock()

        self.window_open = False
        self.window_expires_mono = 0.0
        self.pairing_sessions = {}

        self.controllers = {}

        self.session_id = None
        self.session_token = None
        self.session = None
        self.stream_socket = None
        self.last_sequence = None
        self.lease_until_mono = 0.0
        self.lease_expirations = 0
        self.packets_received = 0
        self.packets_rejected = 0
        self.packets_lost = 0
        self.underruns = 0

        self.wifi_connected = True
        self.wifi_retry = 0
        self.wifi_backoff_s = 0.0
        self.wifi_reconnects = 0

        log.info("Simulator initialized: %s (%s)", self.server_id, config["service"])

    @property
    def server_id(self):
        return self.config["server_id"]

    @property
    def michi_id(self):
        return self.config["michi_id"]

    @property
    def public_key(self):
        return self.config["public_key"]

    def _now(self):
        return self.mono_clock()

    def _now_wall(self):
        return self.wall_clock()

    def _rfc3339(self, epoch_seconds):
        dt = datetime.fromtimestamp(epoch_seconds, tz=timezone.utc)
        return dt.isoformat(timespec="seconds").replace("+00:00", "Z")

    def info(self):
        return dict(self.config)

    # ── Pairing ─────────────────────────────────────────────

    def open_pairing_window(self):
        self.window_open = True
        self.window_expires_mono = self._now() + PAIRING_WINDOW_SECONDS
        self.pairing_sessions.clear()
        log.info("Pairing window OPEN (expires in %ds)", PAIRING_WINDOW_SECONDS)

    def _window_active(self):
        if self.window_open and self._now() >= self.window_expires_mono:
            self.window_open = False
            log.info("Pairing window EXPIRED (closed on contact)")
        return self.window_open

    def _validate_pair_challenge(self, payload):
        """Validate the pairing challenge (contract section 2.3).

        Verifies that `challenge_signature` is a valid Ed25519 signature over
        the DECODED bytes of `challenge_nonce` using the request `public_key`,
        and that `michi_id` corresponds to `public_key` with the exact
        michi-identity derivation: base64url-nopad(blake3(public_key_bytes)).
        """
        try:
            nonce_bytes = decode_base64url_strict(payload["challenge_nonce"])
        except (ValueError, KeyError):
            return RequestError("challenge_nonce must be strict base64url without padding", "challenge_nonce")
        try:
            public_key_bytes = decode_base64url_strict(payload["public_key"])
        except (ValueError, KeyError):
            return RequestError("public_key must be strict base64url without padding", "public_key")
        if len(public_key_bytes) != 32:
            return RequestError("public_key must be a 32-byte Ed25519 public key", "public_key")
        try:
            signature_bytes = decode_base64url_strict(payload["challenge_signature"])
        except (ValueError, KeyError):
            return RequestError("challenge_signature must be strict base64url without padding", "challenge_signature")
        try:
            public_key_obj = Ed25519PublicKey.from_public_bytes(public_key_bytes)
            public_key_obj.verify(signature_bytes, nonce_bytes)
        except InvalidSignature:
            return RequestError("challenge signature does not verify over the decoded nonce", "challenge_signature")
        except ValueError:
            return RequestError("invalid Ed25519 signature encoding", "challenge_signature")
        try:
            michi_id_bytes = decode_base64url_strict(payload["michi_id"])
        except (ValueError, KeyError):
            return RequestError("michi_id must be strict base64url without padding", "michi_id")
        if len(michi_id_bytes) != 32:
            return RequestError("michi_id must be 32 bytes (43 base64url chars)", "michi_id")
        derived = derive_michi_id(public_key_bytes)
        if not hmac.compare_digest(derived, payload["michi_id"]):
            return RequestError("michi_id does not correspond to the provided public_key", "michi_id")
        return None

    def pairing_start(self, payload):
        if not self._window_active():
            return 403, error_body("FORBIDDEN", "The physical pairing window is closed")
        challenge_error = self._validate_pair_challenge(payload)
        if challenge_error is not None:
            log.warning("Pair challenge REJECTED (%s)", challenge_error.field)
            return 400, error_body(
                "INVALID_REQUEST", challenge_error.message, {"field": challenge_error.field}
            )
        session_id = str(uuid.uuid4())
        pin = f"{secrets.randbelow(1000000):06d}"
        session = {
            "session_id": session_id,
            "pin": pin,
            "attempts_remaining": MAX_PIN_ATTEMPTS,
            "status": "pending",
            "controller": dict(payload),
            "expires_mono": self.window_expires_mono,
            "expires_at": self._rfc3339(self._now_wall() + PAIRING_WINDOW_SECONDS),
        }
        self.pairing_sessions[session_id] = session
        log.info("Pairing session created: %s (PIN displayed locally)", session_id)
        return 201, {
            "session_id": session_id,
            "expires_at": session["expires_at"],
            "attempts_remaining": MAX_PIN_ATTEMPTS,
            "server_michi_id": self.michi_id,
            "server_public_key": self.public_key,
        }

    def pairing_status(self, session_id):
        session = self.pairing_sessions.get(session_id)
        if session is None:
            return 404, error_body("NOT_FOUND", "The pairing session was not found")
        if session["status"] == "pending" and self._now() >= session["expires_mono"]:
            status = "expired"
        else:
            status = session["status"]
        return 200, {
            "session_id": session_id,
            "status": status,
            "expires_at": session["expires_at"],
            "attempts_remaining": session["attempts_remaining"],
        }

    def pairing_confirm(self, session_id, pin, michi_id, public_key):
        session = self.pairing_sessions.get(session_id)
        if session is None:
            return 404, error_body("PAIRING_NOT_FOUND", "The pairing session was not found or has expired")
        if session["status"] == "confirmed":
            return 409, error_body("PAIRING_ALREADY_CONSUMED", "This pairing session has already been used")
        if session["status"] == "locked":
            return 429, error_body("RATE_LIMITED", "PIN attempts exceeded for this pairing session")
        if self._now() >= session["expires_mono"]:
            return 404, error_body("PAIRING_NOT_FOUND", "The pairing session was not found or has expired")
        controller = session["controller"]
        if michi_id != controller["michi_id"]:
            return 400, error_body("INVALID_REQUEST", "michi_id does not match the pairing session", {"field": "michi_id"})
        if public_key != controller["public_key"]:
            return 400, error_body("INVALID_REQUEST", "public_key does not match the pairing session", {"field": "public_key"})
        if not hmac.compare_digest(pin, session["pin"]):
            session["attempts_remaining"] -= 1
            if session["attempts_remaining"] <= 0:
                session["status"] = "locked"
                return 429, error_body("RATE_LIMITED", "PIN attempts exceeded; pairing session is locked")
            return 401, error_body("PAIRING_PIN_MISMATCH", "The provided PIN does not match this pairing session")
        session["status"] = "confirmed"
        token = base64.urlsafe_b64encode(secrets.token_bytes(TOKEN_BYTES)).decode("ascii").rstrip("=")
        digest = hashlib.sha256(token.encode("utf-8")).hexdigest()
        device_id = str(uuid.uuid4())
        now_wall = self._now_wall()
        self.controllers[device_id] = {
            "device_id": device_id,
            "michi_id": michi_id,
            "public_key": public_key,
            "token_sha256": digest,
            "permissions": ["receiver.status", "receiver.session", "receiver.volume", "receiver.now_playing"],
            "created_at": now_wall,
            "last_activity": now_wall,
        }
        log.info("Pairing CONFIRMED: controller=%s device=%s", michi_id, device_id)
        return 200, {
            "token": token,
            "expires_in": 0,
            "device_id": device_id,
            "server_id": self.server_id,
        }

    def validate_pairing_token(self, token):
        digest = hashlib.sha256(token.encode("utf-8")).hexdigest()
        return any(
            hmac.compare_digest(digest, controller["token_sha256"])
            for controller in self.controllers.values()
        )

    # ── Session ─────────────────────────────────────────────

    def _allocate_stream_port(self):
        total = STREAM_PORT_MAX - STREAM_PORT_MIN + 1
        start = STREAM_PORT_MIN + secrets.randbelow(total)
        for offset in range(total):
            port = STREAM_PORT_MIN + (start - STREAM_PORT_MIN + offset) % total
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            try:
                sock.bind(("0.0.0.0", port))
                return sock, port
            except OSError:
                sock.close()
        return None, None

    def session_create(self, payload, source_ip):
        self.expire_session_if_needed()
        if self.session_id is not None:
            return 409, error_body("CONFLICT", "A session already exists")
        sock, port = self._allocate_stream_port()
        if sock is None:
            return 500, error_body("INTERNAL_ERROR", "could not allocate a UDP stream port")
        session_id = str(uuid.uuid4())
        session_token = base64.urlsafe_b64encode(secrets.token_bytes(TOKEN_BYTES)).decode("ascii").rstrip("=")
        self.session_id = session_id
        self.session_token = session_token
        self.stream_socket = sock
        self.session = {
            "transport": payload["transport"],
            "codec": payload["codec"],
            "sample_rate": payload["sample_rate"],
            "bit_depth": payload["bit_depth"],
            "channels": payload["channels"],
            "packet_ms": payload["packet_ms"],
            "buffer_ms": payload["buffer_ms"],
            "payload_type": payload["payload_type"],
            "ssrc": payload["ssrc"],
            "volume": payload["volume"],
            "stream_port": port,
            "source_ip": source_ip,
            "paused": False,
        }
        self.last_sequence = None
        self.lease_until_mono = self._now() + SESSION_LEASE_SECONDS
        self.packets_received = 0
        self.packets_rejected = 0
        self.packets_lost = 0
        self.underruns = 0
        log.info("Session STARTED: id=%s port=%d peer=%s", session_id, port, source_ip)
        return 201, {
            "session_id": session_id,
            "session_token": session_token,
            "lease_seconds": SESSION_LEASE_SECONDS,
            "effective": {
                "transport": payload["transport"],
                "codec": payload["codec"],
                "sample_rate": payload["sample_rate"],
                "bit_depth": payload["bit_depth"],
                "channels": payload["channels"],
                "packet_ms": payload["packet_ms"],
                "buffer_ms": payload["buffer_ms"],
                "payload_type": payload["payload_type"],
                "ssrc": payload["ssrc"],
                "stream_port": port,
                "volume": payload["volume"],
            },
        }

    def _state_name(self):
        return "paused" if self.session["paused"] else "playing"

    def session_state(self):
        self.expire_session_if_needed()
        if self.session_id is None:
            return 404, error_body("NOT_FOUND", "session not found")
        remaining = max(0, int((self.lease_until_mono - self._now()) * 1000))
        return 200, {
            "session_id": self.session_id,
            "state": self._state_name(),
            "lease_remaining_ms": remaining,
            "volume": self.session["volume"],
            "paused": self.session["paused"],
            "stream_port": self.session["stream_port"],
            "ssrc": self.session["ssrc"],
            "packets_received": self.packets_received,
            "packets_rejected": self.packets_rejected,
            "packets_lost": self.packets_lost,
            "underruns": self.underruns,
        }

    def session_patch(self, changes):
        self.expire_session_if_needed()
        if self.session_id is None:
            return 404, error_body("NOT_FOUND", "session not found")
        if "volume" in changes:
            self.session["volume"] = changes["volume"]
        if "paused" in changes:
            self.session["paused"] = changes["paused"]
        status, body = self.session_state()
        return status, body

    def session_delete(self):
        self.expire_session_if_needed()
        if self.session_id is None:
            return 404, error_body("NOT_FOUND", "session not found")
        self._release_session(by_lease=False)
        return 204, None

    def heartbeat(self, session_id, sequence):
        self.expire_session_if_needed()
        if self.session_id is None:
            return 404, error_body("NOT_FOUND", "session not found")
        if session_id != self.session_id:
            return 404, error_body("NOT_FOUND", "session not found")
        if self.last_sequence is not None and sequence <= self.last_sequence:
            return 409, error_body("CONFLICT", "heartbeat sequence already seen")
        self.last_sequence = sequence
        self.lease_until_mono = self._now() + SESSION_LEASE_SECONDS
        uptime = int((self._now() - self.boot_mono) * 1000)
        return 200, {
            "session_id": self.session_id,
            "status": "alive",
            "lease_seconds": SESSION_LEASE_SECONDS,
            "receiver_uptime_ms": uptime,
        }

    def session_token_valid(self, header):
        return bool(self.session_token) and hmac.compare_digest(header, self.session_token)

    def expire_session_if_needed(self):
        if self.session_id is not None and self._now() >= self.lease_until_mono:
            self._release_session(by_lease=True)

    def _release_session(self, by_lease):
        session_id = self.session_id
        if self.stream_socket is not None:
            self.stream_socket.close()
        self.session_id = None
        self.session_token = None
        self.session = None
        self.stream_socket = None
        self.last_sequence = None
        self.lease_until_mono = 0.0
        if by_lease:
            self.lease_expirations += 1
        log.info("Session CLOSED: id=%s (%s)", session_id, "lease expired" if by_lease else "delete")

    # ── Network model ───────────────────────────────────────

    def wifi_link_loss(self):
        self.wifi_connected = False
        self.wifi_retry = 0

    def wifi_next_backoff(self):
        if self.wifi_connected:
            return 0.0
        self.wifi_retry += 1
        self.wifi_backoff_s = min(
            WIFI_BACKOFF_BASE_S * (2 ** (self.wifi_retry - 1)),
            WIFI_BACKOFF_MAX_S,
        )
        return self.wifi_backoff_s

    def wifi_reconnect_ok(self):
        self.wifi_connected = True
        self.wifi_retry = 0
        self.wifi_reconnects += 1


class RtpJitterBufferModel:
    """RTP jitter buffer behavior model (firmware michi_audio).

    Feed packets with their RTP sequence number; the model classifies each
    arrival and keeps the firmware metrics: in-order arrival -> played, gap
    vs the expected seq -> lost (silence fills the gap) + played, late
    arrival of a seq below the expected one -> reordered, repeat of a seen
    seq -> duplicate.
    """

    def __init__(self, silence_ms_per_pkt: float = 20.0):
        self.silence_ms_per_pkt = silence_ms_per_pkt
        self.next_expected = None
        self.seen = set()
        self.received = 0
        self.played = 0
        self.lost = 0
        self.reordered = 0
        self.duplicate = 0
        self.silence_ms = 0.0

    def push(self, seq: int) -> str:
        self.received += 1
        if self.next_expected is None:
            self.next_expected = seq + 1
            self.played += 1
            self.seen.add(seq)
            return "played"
        if seq == self.next_expected:
            self.played += 1
            self.next_expected += 1
            self.seen.add(seq)
            return "played"
        if seq < self.next_expected:
            if seq in self.seen:
                self.duplicate += 1
                return "duplicate"
            self.reordered += 1
            self.seen.add(seq)
            return "reordered"
        gap = seq - self.next_expected
        self.lost += gap
        self.silence_ms += gap * self.silence_ms_per_pkt
        self.played += 1
        self.next_expected = seq + 1
        self.seen.add(seq)
        return "silence"

    def metrics(self) -> dict:
        return {
            "received": self.received,
            "played": self.played,
            "lost": self.lost,
            "reordered": self.reordered,
            "duplicate": self.duplicate,
            "silence_ms": round(self.silence_ms, 1),
        }


class OtaModel:
    """OTA lifecycle model (firmware michi_ota)."""

    STATES = ("idle", "fetching", "validating", "downloading",
              "verifying", "applying", "done", "failed")

    def __init__(self):
        self.state = "idle"
        self.percent = 0
        self.error = ""

    def start(self, url: str) -> tuple:
        if self.state != "idle":
            return (False, "busy")
        self.state = "fetching"
        self.percent = 5
        return (True, "started")

    def download(self, percent: int) -> bool:
        if self.state in ("done", "failed"):
            return False
        self.state = "downloading"
        self.percent = percent
        return True

    def fail(self, err: str):
        self.state = "failed"
        self.error = err

    def finish(self):
        self.state = "done"
        self.percent = 100


def create_app(state: SimulatorState) -> Flask:
    app = Flask(__name__)

    def bearer_token():
        header = request.headers.get("Authorization", "")
        if not header.startswith("Bearer "):
            return None
        return header[7:]

    def bearer_guard():
        token = bearer_token()
        if token is None or not state.validate_pairing_token(token):
            log.warning("Auth FAILED (missing or invalid bearer token)")
            return jsonify(error_body("UNAUTHORIZED", "missing or invalid bearer token")), 401
        return None

    def session_guard(require_session_token):
        guard = bearer_guard()
        if guard is not None:
            return guard
        state.expire_session_if_needed()
        if state.session_id is None:
            return jsonify(error_body("NOT_FOUND", "session not found")), 404
        if require_session_token:
            header = request.headers.get("X-Michi-Session", "")
            if not header or not state.session_token_valid(header):
                return jsonify(error_body("UNAUTHORIZED", "missing or invalid session token")), 401
        return None

    def json_payload():
        payload = request.get_json(silent=True)
        if not isinstance(payload, dict):
            return None
        return payload

    @app.route("/api/v1/server/info", methods=["GET"])
    def server_info():
        return jsonify(state.info())

    @app.route("/api/v1/pair/start", methods=["POST"])
    def pair_start():
        payload = json_payload()
        if payload is None:
            return jsonify(error_body("INVALID_REQUEST", "request body must be a JSON object", {"field": "body"})), 400
        err = validate_request("pair-start.schema.json", payload)
        if err is not None:
            return jsonify(error_body("INVALID_REQUEST", err.message, {"field": err.field})), 400
        status, body = state.pairing_start(payload)
        return jsonify(body), status

    @app.route("/api/v1/pair/status", methods=["GET"])
    def pair_status():
        session_id = request.args.get("session_id")
        if not session_id:
            return jsonify(error_body("INVALID_REQUEST", "session_id query parameter is required", {"field": "session_id"})), 400
        status, body = state.pairing_status(session_id)
        return jsonify(body), status

    @app.route("/api/v1/pair/confirm", methods=["POST"])
    def pair_confirm():
        payload = json_payload()
        if payload is None:
            return jsonify(error_body("INVALID_REQUEST", "request body must be a JSON object", {"field": "body"})), 400
        err = validate_request("pair-confirm.schema.json", payload)
        if err is not None:
            return jsonify(error_body("INVALID_REQUEST", err.message, {"field": err.field})), 400
        status, body = state.pairing_confirm(
            payload["session_id"], payload["pin"], payload["michi_id"], payload["public_key"]
        )
        return jsonify(body), status

    @app.route("/api/v1/receiver-lite/session", methods=["POST"])
    def session_create():
        guard = bearer_guard()
        if guard is not None:
            return guard
        payload = json_payload()
        if payload is None:
            return jsonify(error_body("INVALID_REQUEST", "request body must be a JSON object", {"field": "body"})), 400
        err = validate_request("receiver-session-create.schema.json", payload)
        if err is not None:
            return jsonify(error_body("INVALID_REQUEST", err.message, {"field": err.field})), 400
        status, body = state.session_create(payload, request.remote_addr or "0.0.0.0")
        return jsonify(body), status

    @app.route("/api/v1/receiver-lite/session", methods=["GET"])
    def session_get():
        guard = bearer_guard()
        if guard is not None:
            return guard
        status, body = state.session_state()
        return jsonify(body), status

    @app.route("/api/v1/receiver-lite/session", methods=["PATCH"])
    def session_patch():
        guard = session_guard(require_session_token=True)
        if guard is not None:
            return guard
        payload = json_payload()
        if payload is None:
            return jsonify(error_body("INVALID_REQUEST", "request body must be a JSON object", {"field": "body"})), 400
        err = validate_request("receiver-session-patch.schema.json", payload)
        if err is not None:
            return jsonify(error_body("INVALID_REQUEST", err.message, {"field": err.field})), 400
        status, body = state.session_patch(payload)
        return jsonify(body), status

    @app.route("/api/v1/receiver-lite/session", methods=["DELETE"])
    def session_delete():
        guard = session_guard(require_session_token=True)
        if guard is not None:
            return guard
        status, body = state.session_delete()
        if status == 204:
            return "", 204
        return jsonify(body), status

    @app.route("/api/v1/receiver-lite/heartbeat", methods=["POST"])
    def heartbeat():
        guard = session_guard(require_session_token=True)
        if guard is not None:
            return guard
        payload = json_payload()
        if payload is None:
            return jsonify(error_body("INVALID_REQUEST", "request body must be a JSON object", {"field": "body"})), 400
        err = validate_request("receiver-heartbeat.schema.json", payload)
        if err is not None:
            return jsonify(error_body("INVALID_REQUEST", err.message, {"field": err.field})), 400
        status, body = state.heartbeat(payload["session_id"], payload["sequence"])
        return jsonify(body), status

    @app.errorhandler(404)
    def route_not_found(_error):
        return jsonify(error_body("NOT_FOUND", "The requested resource was not found")), 404

    return app


def preinit_session(state):
    state.open_pairing_window()
    _, started = state.pairing_start(CONTROLLER_IDENTITY)
    session_id = started["session_id"]
    pin = state.pairing_sessions[session_id]["pin"]
    _, confirmed = state.pairing_confirm(
        session_id, pin, CONTROLLER_IDENTITY["michi_id"], CONTROLLER_IDENTITY["public_key"]
    )
    pairing_token = confirmed["token"]
    _, created = state.session_create(
        {
            "transport": "rtp_udp",
            "codec": "pcm_s16le",
            "sample_rate": 48000,
            "bit_depth": 16,
            "channels": 2,
            "packet_ms": 10,
            "buffer_ms": 250,
            "payload_type": 97,
            "ssrc": 305419896,
            "volume": 70,
        },
        source_ip="127.0.0.1",
    )
    return pairing_token, created["session_token"], created["session_id"]


def main():
    parser = argparse.ArgumentParser(description="Michi Music Stream Simulator v1-lite")
    parser.add_argument("--config", "-c", type=str, help="Path to JSON config file")
    parser.add_argument("--type", "-t", choices=["standard", "hifi"], default="standard",
                        help="Receiver type (ignored if --config is given)")
    parser.add_argument("--port", "-p", type=int, default=8080, help="HTTP port")
    parser.add_argument("--host", default="0.0.0.0", help="Bind address")
    parser.add_argument("--debug", action="store_true", help="Flask debug mode")
    parser.add_argument("--pairing-open", action="store_true",
                        help="Start with pairing window open (120s)")
    parser.add_argument("--pairing-closed", action="store_true",
                        help="Start with pairing window closed (default)")
    parser.add_argument("--active-session", action="store_true",
                        help="Start with a paired controller and active session")
    parser.add_argument("--fail-heartbeat", action="store_true",
                        help="Start with an active session whose lease is already expired")

    args = parser.parse_args()

    if args.config:
        with open(args.config) as f:
            cfg = json.load(f)
    else:
        cfg = HIFI_CONFIG if args.type == "hifi" else STANDARD_CONFIG

    state = SimulatorState(cfg)

    if args.pairing_open:
        state.open_pairing_window()
        log.info("  initial mode: pairing window OPEN")

    if args.active_session or args.fail_heartbeat:
        pairing_token, session_token, session_id = preinit_session(state)
        log.info("  initial mode: active session (%s)", session_id)
        log.info("  pairing token: %s", pairing_token)
        log.info("  session token: %s", session_token)
        if args.fail_heartbeat:
            state.lease_until_mono = state._now() - 1.0
            log.info("  initial mode: lease already expired (heartbeat WILL FAIL)")

    app = create_app(state)

    log.info("=" * 60)
    log.info("Michi Music Stream Simulator v1-lite (canonical contract)")
    log.info("  server_id: %s", cfg["server_id"])
    log.info("  service:   %s", cfg["service"])
    log.info("  listening: http://%s:%d", args.host, args.port)
    log.info("  endpoints:")
    log.info("    GET    /api/v1/server/info")
    log.info("    POST   /api/v1/pair/start")
    log.info("    GET    /api/v1/pair/status?session_id=<uuid>")
    log.info("    POST   /api/v1/pair/confirm")
    log.info("    POST   /api/v1/receiver-lite/session   [auth]")
    log.info("    GET    /api/v1/receiver-lite/session   [auth]")
    log.info("    PATCH  /api/v1/receiver-lite/session   [auth + session]")
    log.info("    DELETE /api/v1/receiver-lite/session   [auth + session]")
    log.info("    POST   /api/v1/receiver-lite/heartbeat [auth + session]")
    log.info("=" * 60)

    app.run(host=args.host, port=args.port, debug=args.debug)


if __name__ == "__main__":
    main()
