#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Five geometric-sans styles based on Noto Sans (SIL Open Font License),
 * PROPORTIONAL (per-glyph advance), 1-bit column-major bitmaps stored
 * const in flash:
 *
 *   MICHI_FONT_XS  8 px em (line height 10)
 *   MICHI_FONT_SM  13 px em, Noto Sans Medium (line height 16)
 *   MICHI_FONT_MD  17 px em, Noto Sans Regular (line height 20)
 *   MICHI_FONT_LG  26 px em, Noto Sans Regular (line height 30)
 *   MICHI_FONT_PIN 41 px em, Noto Sans Regular (line height 46) - DIGITS + SPACE + '.' only
 *                  (the '.' exists solely so the ellipsis fallback renders;
 *                  the '…' glyph remaps to '.' and every other unsupported
 *                  char to a space via pin_map).
 *
 * Charset: 192 glyphs:
 *   - 0..94: ASCII 0x20..0x7E (95 glyphs)
 *   - 95..190: Latin-1 Supplement 0x00A0..0x00FF (96 glyphs: á, é, í, ó, ú, ñ, ¿, ¡, etc.)
 *   - 191: Ellipsis '…' (U+2026)
 * All data lives in assets/fonts/michi_ui_fonts_data.h, generated by
 * tools/gen_michi_ui_assets.py (committed; Pillow is a dev-only tool).
 *
 * Bitmap layout: byte = column, bit n = row n (LSB = top row); each glyph
 * occupies width * ceil(height/8) contiguous bytes in the flat bitmap.
 */

/*!< Font identifiers. */
typedef enum michi_ui_font_id {
    MICHI_FONT_XS = 0,
    MICHI_FONT_SM,
    MICHI_FONT_MD,
    MICHI_FONT_LG,
    MICHI_FONT_PIN,
    MICHI_FONT_COUNT,
} michi_ui_font_id_t;

/*!< Entries per glyph table (ASCII 0x20..0x7E + Latin-1 Supplement + ellipsis). */
#define MICHI_UI_FONT_GLYPH_COUNT 192

/*!< Full-charset index of the '…' ellipsis glyph. */
#define MICHI_UI_FONT_ELLIPSIS_INDEX (MICHI_UI_FONT_GLYPH_COUNT - 1)

/**
 * @brief Immutable font descriptor (all members point into flash).
 */
typedef struct michi_ui_font {
    const char *name;       /*!< Short style name (debugging). */
    uint8_t height;         /*!< Em box height in pixels. */
    uint8_t baseline;       /*!< Baseline row from the top of the em box. */
    uint8_t line_height;    /*!< Recommended line height in pixels. */
    uint8_t glyph_count;    /*!< Table entries (192 for every font). */
    const uint8_t *bitmap;  /*!< Flat column-major bitmap. */
    const uint8_t *width;   /*!< Per-glyph bitmap width. */
    const uint8_t *advance; /*!< Per-glyph advance in pixels. */
    const uint16_t *offset; /*!< Per-glyph byte offset into bitmap. */
    uint8_t raster_bits;    /* 1 = on/off, 2 = 4-level coverage */
    uint8_t bytes_per_col;  /* ceil(height * raster_bits / 8) */
    const uint8_t *pin_map; /*!< NULL, or full-index -> glyph remap (PIN). */
} michi_ui_font_t;

/**
 * @brief Return the font for an id (always non-NULL; static flash data).
 */
const michi_ui_font_t *michi_ui_font_get(michi_ui_font_id_t id);

/**
 * @brief Decode the next character into a full-charset index 0..191 and
 *        advance the cursor.
 *
 * ASCII 0x20..0x7E map to 0..94; Latin-1 0x00A0..0x00FF map to 95..190;
 * '…' (U+2026) maps to MICHI_UI_FONT_ELLIPSIS_INDEX (191); control characters
 * render as space; any unsupported codepoint renders as a single '?' (index 31).
 * The cursor always advances the full codepoint bytes (1..4), so no UTF-8 sequence
 * is ever split.
 */
uint8_t michi_ui_font_decode(const michi_ui_font_t *font, const char **cursor);

/**
 * @brief Advance (px) of a full-charset index in this font (PIN remapped).
 */
int michi_ui_font_advance(const michi_ui_font_t *font, uint8_t full_idx);

/**
 * @brief Draw one glyph at LOCAL band coordinates (x, y = top of em box),
 *        clipped per pixel to [0,fb_w) x [0,fb_h). Does not advance.
 */
void michi_ui_font_draw_glyph(uint16_t *fb, uint16_t fb_w, uint16_t fb_h,
                              int x, int y, const michi_ui_font_t *font,
                              uint8_t full_idx, uint16_t color);

/*!< Line height for multiline paragraph layouts. */
static inline int michi_ui_font_line_height(const michi_ui_font_t *font)
{
    if (font == NULL) {
        return 0;
    }
    return (font->line_height != 0) ? (int)font->line_height : (int)font->height;
}

#ifdef __cplusplus
}
#endif
