#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Bitmap typography system (UI redesign, phase UI-01).
 *
 * Five geometric-sans styles, PROPORTIONAL (per-glyph advance), 1-bit
 * column-major bitmaps stored const in flash:
 *
 *   MICHI_FONT_XS  8 px em, hand-designed pixel art (TrueType hinting at
 *                  8 px produces broken strokes; see the generator).
 *   MICHI_FONT_SM  11 px, Google Sans Medium
 *   MICHI_FONT_MD  14 px, Google Sans Regular
 *   MICHI_FONT_LG  20 px, Google Sans Regular
 *   MICHI_FONT_PIN 36 px, Google Sans Regular - DIGITS + SPACE + '.' only
 *                  (the '.' exists solely so the ellipsis fallback renders;
 *                  everything else remaps to a space via pin_map).
 *
 * Charset: ASCII 0x20..0x7E plus '…' (UTF-8 E2 80 A6) at full index 95.
 * All data lives in assets/fonts/michi_ui_fonts_data.h, generated by
 * tools/gen_michi_ui_assets.py (committed; Pillow is a dev-only tool).
 *
 * Bitmap layout: byte = column, bit n = row n (LSB = top row); each glyph
 * occupies width * ceil(height/8) contiguous bytes in the flat bitmap.
 */

/*!< Font identifiers. */
typedef enum michi_ui_font_id {
    MICHI_FONT_XS = 0,
    MICHI_FONT_SM,
    MICHI_FONT_MD,
    MICHI_FONT_LG,
    MICHI_FONT_PIN,
    MICHI_FONT_COUNT,
} michi_ui_font_id_t;

/*!< Entries per glyph table (ASCII 0x20..0x7E + ellipsis). */
#define MICHI_UI_FONT_GLYPH_COUNT 96

/*!< Full-charset index of the '…' ellipsis glyph. */
#define MICHI_UI_FONT_ELLIPSIS_INDEX (MICHI_UI_FONT_GLYPH_COUNT - 1)

/**
 * @brief Immutable font descriptor (all members point into flash).
 */
typedef struct michi_ui_font {
    const char *name;     /*!< Short style name (debugging). */
    uint8_t height;       /*!< Em box height in pixels. */
    uint8_t baseline;     /*!< Baseline row from the top of the em box. */
    uint8_t glyph_count;  /*!< Table entries (96 for every font). */
    const uint8_t *bitmap;  /*!< Flat column-major bitmap. */
    const uint8_t *width;   /*!< Per-glyph bitmap width. */
    const uint8_t *advance; /*!< Per-glyph advance in pixels. */
    const uint16_t *offset; /*!< Per-glyph byte offset into bitmap. */
    const uint8_t *pin_map; /*!< NULL, or full-index -> glyph remap (PIN). */
} michi_ui_font_t;

/**
 * @brief Return the font for an id (always non-NULL; static flash data).
 */
const michi_ui_font_t *michi_ui_font_get(michi_ui_font_id_t id);

/**
 * @brief Decode the next character into a full-charset index 0..95 and
 *        advance the cursor.
 *
 * ASCII 0x20..0x7E map to 0..94; '…' (E2 80 A6) maps to
 * MICHI_UI_FONT_ELLIPSIS_INDEX; control characters render as space; any
 * other byte sequence renders as '?' (index 63). The cursor always advances
 * at least one byte (3 for the ellipsis), so no UTF-8 sequence is ever
 * split.
 */
uint8_t michi_ui_font_decode(const michi_ui_font_t *font, const char **cursor);

/**
 * @brief Advance (px) of a full-charset index in this font (PIN remapped).
 */
int michi_ui_font_advance(const michi_ui_font_t *font, uint8_t full_idx);

/**
 * @brief Draw one glyph at LOCAL band coordinates (x, y = top of em box),
 *        clipped per pixel to [0,fb_w) x [0,fb_h). Does not advance.
 */
void michi_ui_font_draw_glyph(uint16_t *fb, uint16_t fb_w, uint16_t fb_h,
                              int x, int y, const michi_ui_font_t *font,
                              uint8_t full_idx, uint16_t color);

/*!< Em box height (== natural single-line pitch baseline). */
static inline int michi_ui_font_line_height(const michi_ui_font_t *font)
{
    return font->height;
}

#ifdef __cplusplus
}
#endif
